import type { FoodItem, Supplement } from '../types';

export interface MealSlot {
  time: string;
  label: string;
  emoji: string;
  why: string;
  foods: string[];
  protein: number;
  calories: number;
}

export const DAILY_MEAL_PLAN: MealSlot[] = [
  {
    time: '10:00 AM',
    label: 'First Meal',
    emoji: '🍳',
    why: '16:8 window opens here. 3 large meals trigger muscle protein synthesis just as effectively as 6 small ones — each large dose fully activates the MPS response. Start strong with ~65g protein.',
    foods: ['4 whole eggs scrambled', '200g beans (cooked)', '2 slices wholegrain bread', '1 banana'],
    protein: 65,
    calories: 820,
  },
  {
    time: '2:00 PM',
    label: 'Pre-Workout Meal',
    emoji: '🍚',
    why: 'Largest carb meal of the day — 90 min before your afternoon training. Carbs here go straight to glycogen, not fat. Do not train without fuel at 95kg with heavy compounds.',
    foods: ['250g grilled chicken breast', '300g cooked white rice', '1 fried plantain (150g)', '100g cucumber'],
    protein: 78,
    calories: 900,
  },
  {
    time: '6:30 PM',
    label: 'Last Meal',
    emoji: '🥩',
    why: 'Post-workout recovery window. Protein + carbs after training refills glycogen and starts muscle repair. Last meal by 7pm closes your 16:8 window — 16 hours of fat-burning fasting begins.',
    foods: ['200g tilapia or mackerel (grilled)', '250g cooked rice or yam', '150g beans or moi moi', '1 tbsp groundnut oil'],
    protein: 65,
    calories: 780,
  },
];

export const USER_TARGETS = {
  calories: 2500,
  protein: 171,   // 1.8g/kg at 95kg — minimum effective dose for recomposition (Morton et al. 2018: plateau at 1.62g/kg)
  carbs: 292,     // bumped up from 240 to fill the ~116 kcal freed by reducing protein
  fat: 72,
  waterMl: 3500,
  goalWeightKg: 85,
  startWeightKg: 95,
  weeklyGoalKg: 0.6,
};

export const FOOD_LIBRARY: FoodItem[] = [
  // Proteins
  {
    id: 'chicken_breast',
    name: 'Grilled Chicken Breast',
    calories: 165,
    protein: 31,
    carbs: 0,
    fat: 3.6,
    servingSize: '100g',
  },
  {
    id: 'eggs_whole',
    name: 'Whole Eggs',
    calories: 155,
    protein: 13,
    carbs: 1.1,
    fat: 11,
    servingSize: '2 large eggs (100g)',
  },
  {
    id: 'egg_whites',
    name: 'Egg Whites',
    calories: 52,
    protein: 11,
    carbs: 0.7,
    fat: 0.2,
    servingSize: '100g',
  },
  {
    id: 'whey_protein',
    name: 'Whey Protein Shake',
    calories: 120,
    protein: 25,
    carbs: 3,
    fat: 1.5,
    servingSize: '1 scoop (30g)',
  },
  {
    id: 'lean_beef',
    name: 'Lean Beef Mince (90%)',
    calories: 176,
    protein: 26,
    carbs: 0,
    fat: 8,
    servingSize: '100g',
  },
  {
    id: 'tuna_can',
    name: 'Canned Tuna (in water)',
    calories: 116,
    protein: 26,
    carbs: 0,
    fat: 1,
    servingSize: '100g',
  },
  {
    id: 'greek_yogurt',
    name: 'Greek Yogurt (0% fat)',
    calories: 59,
    protein: 10,
    carbs: 3.6,
    fat: 0.4,
    servingSize: '100g',
  },
  {
    id: 'cottage_cheese',
    name: 'Cottage Cheese (low fat)',
    calories: 72,
    protein: 12,
    carbs: 2.7,
    fat: 1,
    servingSize: '100g',
  },
  // Carbs
  {
    id: 'white_rice',
    name: 'White Rice (cooked)',
    calories: 130,
    protein: 2.7,
    carbs: 28,
    fat: 0.3,
    servingSize: '100g',
  },
  {
    id: 'oats',
    name: 'Rolled Oats (dry)',
    calories: 389,
    protein: 17,
    carbs: 66,
    fat: 7,
    servingSize: '100g',
  },
  {
    id: 'sweet_potato',
    name: 'Sweet Potato (baked)',
    calories: 103,
    protein: 2.3,
    carbs: 24,
    fat: 0.1,
    servingSize: '100g',
  },
  {
    id: 'banana',
    name: 'Banana',
    calories: 89,
    protein: 1.1,
    carbs: 23,
    fat: 0.3,
    servingSize: '1 medium (100g)',
  },
  {
    id: 'bread_whole',
    name: 'Wholegrain Bread',
    calories: 247,
    protein: 13,
    carbs: 41,
    fat: 3.4,
    servingSize: '100g',
  },
  // Fats
  {
    id: 'olive_oil',
    name: 'Olive Oil',
    calories: 119,
    protein: 0,
    carbs: 0,
    fat: 13.5,
    servingSize: '1 tbsp (13.5g)',
  },
  {
    id: 'peanut_butter',
    name: 'Peanut Butter (natural)',
    calories: 94,
    protein: 4,
    carbs: 3.5,
    fat: 8,
    servingSize: '1 tbsp (16g)',
  },
  {
    id: 'almonds',
    name: 'Almonds',
    calories: 164,
    protein: 6,
    carbs: 6,
    fat: 14,
    servingSize: '28g (small handful)',
  },
  // Vegetables
  {
    id: 'spinach',
    name: 'Spinach (raw)',
    calories: 23,
    protein: 2.9,
    carbs: 3.6,
    fat: 0.4,
    servingSize: '100g',
  },
  {
    id: 'broccoli',
    name: 'Broccoli (steamed)',
    calories: 35,
    protein: 2.4,
    carbs: 7.2,
    fat: 0.4,
    servingSize: '100g',
  },
  {
    id: 'cucumber',
    name: 'Cucumber',
    calories: 15,
    protein: 0.7,
    carbs: 3.6,
    fat: 0.1,
    servingSize: '100g',
  },
  // Meals (composite)
  // Budget proteins
  {
    id: 'chicken_thighs',
    name: 'Chicken Thighs (boneless)',
    calories: 209,
    protein: 26,
    carbs: 0,
    fat: 11,
    servingSize: '100g',
  },
  {
    id: 'sardines_can',
    name: 'Canned Sardines (in oil, drained)',
    calories: 208,
    protein: 25,
    carbs: 0,
    fat: 12,
    servingSize: '1 tin (100g)',
  },
  {
    id: 'lentils_cooked',
    name: 'Lentils (cooked)',
    calories: 116,
    protein: 9,
    carbs: 20,
    fat: 0.4,
    servingSize: '100g',
  },
  {
    id: 'full_fat_milk',
    name: 'Full-Fat Milk',
    calories: 61,
    protein: 3.2,
    carbs: 4.8,
    fat: 3.3,
    servingSize: '100ml',
  },
  {
    id: 'beans_black',
    name: 'Black Beans (cooked)',
    calories: 132,
    protein: 8.9,
    carbs: 24,
    fat: 0.5,
    servingSize: '100g',
  },
  // Meals (composite)
  {
    id: 'chicken_salad',
    name: 'Chicken Salad (optimal)',
    calories: 435,
    protein: 52,
    carbs: 12,
    fat: 18,
    servingSize: '1 serving (200g chicken + veg + dressing)',
  },
  {
    id: 'rice_chicken_broccoli',
    name: 'Rice + Chicken + Broccoli',
    calories: 540,
    protein: 48,
    carbs: 55,
    fat: 8,
    servingSize: '1 plate (150g rice + 200g chicken + 150g broccoli)',
  },
  {
    id: 'oats_whey_banana',
    name: 'Oats + Whey + Banana',
    calories: 520,
    protein: 38,
    carbs: 72,
    fat: 9,
    servingSize: '100g oats + 1 scoop whey + 1 banana',
  },
  {
    id: 'budget_protein_plate',
    name: 'Thighs + Rice + Lentils',
    calories: 580,
    protein: 46,
    carbs: 58,
    fat: 12,
    servingSize: '150g thighs + 100g rice + 100g lentils',
  },
  {
    id: 'eggs_sardines_toast',
    name: 'Eggs + Sardines + Bread',
    calories: 490,
    protein: 42,
    carbs: 36,
    fat: 18,
    servingSize: '3 eggs + 1 sardine tin + 2 slices bread',
  },
];

export const DEFAULT_SUPPLEMENTS: Supplement[] = [
  {
    id: 'creatine',
    name: 'Creatine Monohydrate',
    dose: '5g',
    timing: 'Any time — consistency matters',
    taken: false,
    notificationTime: '08:00',
  },
  {
    id: 'whey',
    name: 'Whey Protein',
    dose: '30–40g',
    timing: 'Post-workout or when short on protein',
    taken: false,
    notificationTime: undefined,
  },
  {
    id: 'omega3',
    name: 'Omega-3 (Fish Oil)',
    dose: '2–3g EPA+DHA',
    timing: 'With food',
    taken: false,
    notificationTime: '13:00',
  },
  {
    id: 'vitamin_d',
    name: 'Vitamin D3',
    dose: '2,000–4,000 IU',
    timing: 'Morning with food',
    taken: false,
    notificationTime: '08:00',
  },
  {
    id: 'magnesium',
    name: 'Magnesium Glycinate',
    dose: '300–400mg',
    timing: 'Before sleep',
    taken: false,
    notificationTime: '22:00',
  },
  {
    id: 'minoxidil',
    name: 'Minoxidil',
    dose: 'Per prescription',
    timing: 'As scheduled',
    taken: false,
    notificationTime: '08:00',
  },
];
