import type { WorkoutSession, DayOfWeek } from '../types';

/**
 * THE SCULPT SPLIT — 5 sessions, built around four stated priorities:
 *
 *   1. Legs, previously neglected — now the first session of the week, trained
 *      twice, while you are freshest. Priority means position, not just volume.
 *   2. Lower back / erector spinae, previously never trained directly — two
 *      dedicated slots. Deadlifts load the erectors isometrically, which builds
 *      tolerance but very little size. Loaded spinal extension through range is
 *      what actually thickens the column.
 *   3. Chest, two dedicated angles per week, always the first movement of its
 *      session.
 *   4. A genuinely slim waist, which means the core work here is deliberately
 *      NOT what most programmes prescribe. Loaded Russian twists and weighted
 *      side bends hypertrophy the obliques — bigger obliques are a wider waist.
 *      Every rotational/lateral movement in this split is isometric or light by
 *      design: anti-rotation (Pallof), anti-lateral-flexion (suitcase carry),
 *      anti-extension (ab wheel), plus transverse abdominis work (vacuums) that
 *      cinches the midsection inward. Direct rectus abdominis loading stays,
 *      because visible abs need thickness — the obliques are the ones that must
 *      not grow.
 *
 * Day order: Legs A, Push, Pull, rest, Legs B, Upper, rest.
 */

export const WEEKLY_SPLIT: Record<DayOfWeek, WorkoutSession | null> = {
  monday: {
    id: 'legs',
    type: 'legs',
    label: 'Legs A — Quad Drive & Spinal Armour',
    intent:
      'Legs open the week because they were the thing you skipped. First session, freshest nervous system, heaviest loads. Your first direct lower-back work sits here too.',
    exercises: [
      {
        id: 'back_squat',
        name: 'Barbell Back Squat',
        muscleGroups: ['quads', 'glutes', 'hamstrings'],
        sets: 4,
        repsMin: 5,
        repsMax: 8,
        restSeconds: 180,
        compound: true,
        tempo: '3-0-1',
        why: 'Regional hypertrophy studies show the squat grows the vastus lateralis specifically at the 25% and 50% femur sites. Nothing else loads the quad this heavily through a deep hip and knee angle at the same time.',
        notes: 'Depth below parallel or the set does not count. Log the weight every session — this is your primary strength marker.',
        swaps: ['Front Squat', 'Safety Bar Squat'],
      },
      {
        id: 'hack_squat',
        name: 'Hack Squat',
        muscleGroups: ['quads', 'glutes'],
        sets: 3,
        repsMin: 10,
        repsMax: 12,
        restSeconds: 120,
        compound: true,
        why: 'Quad-dominant loading with the torso supported, so you can push genuinely close to failure — the erectors are not the limiting factor here, and they have their own work later in this session.',
        notes: 'Feet low and close on the platform. Full depth, control the negative.',
        swaps: ['Leg Press (feet low and narrow)', 'Smith Machine Squat'],
      },
      {
        id: 'leg_ext',
        name: 'Leg Extension',
        muscleGroups: ['quads'],
        sets: 3,
        repsMin: 12,
        repsMax: 15,
        restSeconds: 75,
        lengthenedPartials: true,
        why: 'The rectus femoris crosses the hip, so it stays slack in every squat pattern and gets almost nothing from them. Leg extensions grow all three of its regions — most at 75% femur length. This is the single biggest gap in a squat-only leg day.',
        notes: 'Hold the top contraction 1 second. Last set: after failure, do 6–8 half reps from the bottom stretched position.',
      },
      {
        id: 'walking_lunge',
        name: 'Walking Dumbbell Lunge',
        muscleGroups: ['quads', 'glutes', 'hamstrings'],
        sets: 3,
        repsMin: 10,
        repsMax: 12,
        restSeconds: 90,
        perSide: true,
        why: 'A long stride loads the glute and adductor magnus far harder than a bilateral squat, and unilateral work exposes the left/right strength gap a barbell hides.',
        notes: 'Reps per leg. Long stride, back knee low, torso upright.',
        swaps: ['Reverse Lunge', 'Step-Up (knee-height box)'],
      },
      {
        id: 'seated_leg_curl_mon',
        name: 'Nordic Hamstring Curl',
        muscleGroups: ['hamstrings'],
        sets: 4,
        repsMin: 6,
        repsMax: 10,
        restSeconds: 90,
        why: 'No seated leg curl machine in this gym, so this is the swap — Maeo 2024 found seated curls out-grow Nordic curls, but Nordic is the next best thing and needs no equipment beyond an anchor for your ankles.',
        notes: 'Kneel, ankles anchored (partner holds them or hook under a pad), lower yourself as slowly as possible under control, catch yourself with your hands at the bottom. The slow lowering is the whole exercise — do not rush it.',
      },
      {
        id: 'back_ext_45',
        name: '45° Back Extension (weighted)',
        muscleGroups: ['lower_back', 'glutes', 'hamstrings'],
        sets: 3,
        repsMin: 12,
        repsMax: 15,
        restSeconds: 90,
        why: 'This is the gap you identified. Deadlifts load the erector spinae isometrically — that builds tolerance, not size. Loaded spinal extension through a full range is what thickens the lower back and removes the flat look from behind.',
        notes: 'Hold a plate at your chest. Round down slowly, extend to a straight line — do not hyperextend past it.',
        swaps: ['Good Morning (light)', 'Hyperextension bench'],
      },
      {
        id: 'standing_calf',
        name: 'Standing Calf Raise',
        muscleGroups: ['calves'],
        sets: 4,
        repsMin: 12,
        repsMax: 15,
        restSeconds: 60,
        lengthenedPartials: true,
        why: 'Gastrocnemius. It only loads with a straight knee, which is why it needs its own slot separate from the seated version on Friday.',
        notes: 'Full stretch at the bottom, 2-second pause. No bouncing.',
      },
      {
        id: 'cable_crunch_mon',
        name: 'Weighted Cable Crunch',
        muscleGroups: ['core'],
        sets: 3,
        repsMin: 12,
        repsMax: 15,
        restSeconds: 60,
        why: 'A direct comparison found the crunch produced 36% greater rectus abdominis thickness change than the leg raise. Abs are muscle — visible abs need thickness, and thickness needs progressive load, not endless bodyweight reps.',
        notes: 'Add weight weekly. Curl the spine down rib-to-hip — this is not a hip hinge.',
      },
      {
        id: 'vacuum_mon',
        name: 'Stomach Vacuum',
        muscleGroups: ['deep_core'],
        sets: 3,
        repsMin: 20,
        repsMax: 30,
        restSeconds: 45,
        bodyweight: true,
        isTimed: true,
        why: 'Trains the transverse abdominis — the deep corset layer that pulls the midsection inward. It burns almost no calories and it is not fat loss; what it does is change how your waist sits at any given body fat. It is the closest thing to a genuine waist-narrowing exercise that exists.',
        notes: 'Seconds held. Exhale everything out, pull the navel back toward the spine, hold. Do it fasted for the strongest contraction.',
      },
    ],
    warmUp: [
      { name: 'Hip Circles', duration: '10 reps each direction', description: 'Stand on one foot, draw large circles with the raised knee. Mobilises the hip capsule in all planes before squatting and reduces femoral impingement at depth.' },
      { name: 'Leg Swings', duration: '10 reps each direction per leg', description: 'Hold a wall. Swing one leg forward and back, then side to side. Warms the hip flexors, hamstrings and adductors dynamically before any load.' },
      { name: 'Deep Bodyweight Squat Hold', duration: '3 × 30 secs', description: 'Sink to the bottom of a squat, heels flat, knees tracking toes. Exposes mobility restrictions before you load them and opens the ankles and hip flexors.' },
      { name: 'Cat-Cow', duration: '10 slow reps', description: 'On hands and knees, alternate arching and rounding the spine. Wakes the erector spinae through its full range — critical today because you are about to train it directly for the first time.' },
      { name: 'Glute Bridges', duration: '20 reps slow', description: 'Drive the hips up, hard squeeze at the top. Activates the glutes so the lower back does not take over during squats.' },
      { name: 'Warm-Up Squat Sets', duration: '3 ramping sets', description: 'Empty bar × 10, then roughly 40% and 60% of your working weight for 5. Grooves the pattern and primes the joints before the first heavy set.' },
    ],
    coolDown: [
      { name: 'Standing Quad Stretch', duration: '45 secs each side', description: 'Stand on one leg, pull the other heel to your glute, keep the knees together. Quads carry the bulk of today\'s load — restoring resting length reduces next-day stiffness.' },
      { name: 'Supine Hamstring Stretch', duration: '45 secs each side', description: 'Lie on your back, pull one leg toward your chest as straight as you can. Necessary after seated curls, which train the hamstring in a deeply shortened-to-lengthened range.' },
      { name: 'Child\'s Pose', duration: '60 secs', description: 'Kneel, sit back on heels, arms extended forward. Decompresses the spine and lengthens the erectors after their first direct loading of the week.' },
      { name: 'Pigeon Pose (Figure-4)', duration: '60 secs each side', description: 'Cross one ankle over the opposite knee, pull both toward the chest. Releases the piriformis and glute medius compressed under heavy squatting.' },
      { name: 'Standing Calf Stretch', duration: '30 secs each side', description: 'Foot flat, straight knee, lean into a wall. Restricted ankle dorsiflexion caps squat depth — this directly addresses it.' },
    ],
  },

  tuesday: {
    id: 'push',
    type: 'push',
    label: 'Push — Chest Architecture',
    intent:
      'Three chest angles in priority order: upper, mid, lower. Chest is a growth target, so it takes the first three slots while you are fresh. Delts get real volume because shoulder width is the other half of a narrow-looking waist.',
    exercises: [
      {
        id: 'incline_db_press',
        name: 'Incline Dumbbell Press',
        muscleGroups: ['chest', 'shoulders'],
        sets: 4,
        repsMin: 6,
        repsMax: 10,
        restSeconds: 150,
        compound: true,
        tempo: '3-1-1',
        why: 'A 2020 JSCR comparison of seven chest exercises found the incline dumbbell press produced the highest clavicular (upper) pec activation of all of them. The upper chest is what builds the shelf under the collarbone, so it goes first, on your freshest effort.',
        notes: 'Bench at 30°. Higher than that and it becomes a shoulder press. Full stretch at the bottom.',
        swaps: ['Incline Machine Press', 'Incline Smith Press'],
      },
      {
        id: 'bench_press',
        name: 'Barbell Bench Press',
        muscleGroups: ['chest', 'shoulders', 'triceps'],
        sets: 4,
        repsMin: 6,
        repsMax: 8,
        restSeconds: 150,
        compound: true,
        why: 'Flat pressing recruits roughly 30% more sternal (mid and lower) pec than incline. No single press angle builds a complete chest — you need both, and this is the one you can load heaviest.',
        notes: 'Shoulder blades pinned back and down. Touch the chest, no bounce. Primary strength lift — log it.',
      },
      {
        id: 'weighted_dip',
        name: 'Weighted Dip (chest-biased)',
        muscleGroups: ['chest', 'triceps'],
        sets: 3,
        repsMin: 8,
        repsMax: 10,
        restSeconds: 120,
        compound: true,
        why: 'Loads the lower sternal fibres that build the defined line under the pec — the border that only shows up when you are lean, which is exactly where you are heading.',
        notes: 'Lean the torso forward about 30° and let the elbows flare slightly. Upright and it becomes a triceps exercise.',
        swaps: ['Decline Barbell Press', 'Assisted Dip Machine'],
      },
      {
        id: 'low_high_fly',
        name: 'Low-to-High Cable Fly',
        muscleGroups: ['chest'],
        sets: 3,
        repsMin: 12,
        repsMax: 15,
        restSeconds: 75,
        lengthenedPartials: true,
        why: 'The only chest movement that keeps tension on the pec at full stretch. A 2025 meta-analysis of 8 studies found training at long muscle lengths beat short-length training for hypertrophy (ES 0.283, p = 0.036). Presses lose tension at the bottom; this does not.',
        notes: 'Cables set low, sweep up and in to meet at collarbone height. Last set: 8 half reps in the stretched position after failure.',
      },
      {
        id: 'seated_ohp',
        name: 'Seated Dumbbell Overhead Press',
        muscleGroups: ['shoulders', 'triceps'],
        sets: 3,
        repsMin: 6,
        repsMax: 10,
        restSeconds: 120,
        compound: true,
        why: 'Front and lateral delt under heavy load. Dumbbells over a barbell here because the pressing volume this block is already high and the free path is easier on the shoulder.',
        notes: 'Back supported, strict — no leg drive, no lower back arch.',
      },
      {
        id: 'lateral_raises_tue',
        name: 'Lateral Raise',
        muscleGroups: ['shoulders'],
        sets: 4,
        repsMin: 12,
        repsMax: 15,
        restSeconds: 60,
        why: 'Shoulder width is the other half of a slim waist. The eye reads the shoulder-to-waist ratio, not the waist alone — 2 cm of extra delt does as much for your taper as 2 cm off the waist, and unlike the waist you can build it during the deficit.',
        notes: '3-second lowering, no swing. If you need momentum the weight is wrong.',
      },
      {
        id: 'oh_tricep_ext',
        name: 'Overhead Cable Tricep Extension',
        muscleGroups: ['triceps'],
        sets: 3,
        repsMin: 10,
        repsMax: 12,
        restSeconds: 60,
        lengthenedPartials: true,
        why: 'The triceps long head crosses the shoulder, so it only reaches full stretch with the arm overhead. Pushdowns alone leave the biggest of the three heads undertrained.',
        notes: 'Elbows tight, full stretch behind the head.',
      },
      {
        id: 'rope_pushdown',
        name: 'Rope Pushdown',
        muscleGroups: ['triceps'],
        sets: 3,
        repsMin: 12,
        repsMax: 15,
        restSeconds: 60,
        notes: 'Spread the rope at the bottom, hard lockout.',
      },
      {
        id: 'hanging_leg_raise_tue',
        name: 'Hanging Leg Raise',
        muscleGroups: ['core'],
        sets: 3,
        repsMin: 12,
        repsMax: 15,
        restSeconds: 60,
        bodyweight: true,
        why: 'Biases the lower rectus abdominis — the region that stays hidden longest and the one you specifically want visible. It does not burn the fat off your lower stomach, but it builds the muscle that shows once the fat is gone.',
        notes: 'Curl the pelvis up at the top. If your legs only swing, the abs are not doing the work — bend the knees and slow down.',
      },
    ],
    warmUp: [
      { name: 'Arm Circles', duration: '30 secs each direction', description: 'Large forward then backward circles. Mobilises the shoulder joint and warms the rotator cuff before any pressing load.' },
      { name: 'Band Pull-Aparts', duration: '20 reps', description: 'Band at shoulder width, arms straight, pull apart to the chest. Activates rear delts and opens the anterior shoulder — cuts impingement risk on bench and overhead work.' },
      { name: 'Doorway Chest Opener', duration: '30 secs each side', description: 'Forearm on the frame, elbow at shoulder height, lean through. Increases pec minor flexibility so you can reach a full stretch on the first working set rather than the fourth.' },
      { name: 'Scapular Push-Ups', duration: '15 reps', description: 'Plank position, protract and retract the shoulder blades with straight arms. Activates the serratus anterior, which stabilises the scapula on every press rep.' },
      { name: 'Ramping Incline Sets', duration: '2 × 12 light', description: 'Two light sets on the first movement. Primes the neuromuscular pattern for the priority lift instead of wasting your best sets warming up.' },
    ],
    coolDown: [
      { name: 'Doorway Chest Stretch (held)', duration: '45 secs each side', description: 'Same position as the warm-up, held longer. Static stretching after training restores resting pec length and reduces next-day tightness.' },
      { name: 'Lying Pec Stretch', duration: '45 secs each side', description: 'Face down, one arm extended sideways at shoulder height, roll gently onto that side. The deepest available stretch of the sternal pec head.' },
      { name: 'Cross-Body Shoulder Stretch', duration: '30 secs each side', description: 'Pull one straight arm across the chest. Releases the posterior capsule after heavy lateral raise volume.' },
      { name: 'Overhead Tricep Stretch', duration: '30 secs each side', description: 'Arm overhead, elbow bent, press it gently down with the opposite hand. Targets the long head, the most-loaded head today.' },
    ],
  },

  wednesday: {
    id: 'pull',
    type: 'pull',
    label: 'Pull — Width, Thickness & The Hinge',
    intent:
      'Lats build the taper from above. Deadlifts hammer the whole posterior chain. The core work here is all anti-rotation and anti-lateral-flexion — trunk strength without oblique growth.',
    exercises: [
      {
        id: 'deadlift',
        name: 'Conventional Deadlift',
        muscleGroups: ['back', 'lower_back', 'hamstrings', 'glutes'],
        sets: 4,
        repsMin: 4,
        repsMax: 6,
        restSeconds: 210,
        compound: true,
        why: 'The heaviest loading the erector spinae will ever see. It builds tolerance and thickness through the whole posterior chain — but it works the lower back isometrically, which is why it does not replace the direct extension work on Monday and Friday.',
        notes: 'Heaviest lift of the week. Brace hard, bar against the shins, hips and shoulders rise together.',
        swaps: ['Trap Bar Deadlift', 'Rack Pull (below knee)'],
      },
      {
        id: 'weighted_pullups',
        name: 'Weighted Pull-Up',
        muscleGroups: ['back', 'biceps'],
        sets: 4,
        repsMin: 6,
        repsMax: 10,
        restSeconds: 150,
        compound: true,
        why: 'Lat width is what makes a waist read as narrow from the front. The taper is built here as much as it is built by losing fat — you are widening the top of the V while the bottom comes in.',
        notes: 'Add weight once you can do 10 clean reps. Dead hang at the bottom every rep.',
        swaps: ['Lat Pulldown (wide grip)', 'Assisted Pull-Up Machine'],
      },
      {
        id: 'chest_supported_row',
        name: 'Chest-Supported Row',
        muscleGroups: ['back'],
        sets: 4,
        repsMin: 10,
        repsMax: 12,
        restSeconds: 90,
        compound: true,
        why: 'Mid-back thickness with the pad taking the erectors out of the movement — so this does not eat into the recovery budget that Monday and Friday\'s direct lower-back work needs.',
        notes: 'Chest stays on the pad. Pull to the lower ribs, squeeze the blades together.',
        swaps: ['Seal Row', 'Machine Row'],
      },
      {
        id: 'single_arm_pulldown',
        name: 'Half-Kneeling Single-Arm Lat Pulldown',
        muscleGroups: ['back', 'core'],
        sets: 3,
        repsMin: 12,
        repsMax: 15,
        restSeconds: 60,
        perSide: true,
        lengthenedPartials: true,
        why: 'Full overhead lat stretch that a bilateral bar restricts, plus an anti-rotation demand through the trunk on every rep — two jobs from one movement.',
        notes: 'Reps per side. Let the shoulder travel all the way up at the top.',
      },
      {
        id: 'face_pulls',
        name: 'Face Pull',
        muscleGroups: ['shoulders', 'back'],
        sets: 3,
        repsMin: 15,
        repsMax: 20,
        restSeconds: 60,
        why: 'Rear delts and external rotators. Non-negotiable — this is what keeps your shoulders healthy under the pressing volume this block carries.',
        notes: 'Pull to the forehead, elbows high, externally rotate at the end.',
      },
      {
        id: 'bb_curl',
        name: 'Barbell Curl',
        muscleGroups: ['biceps'],
        sets: 3,
        repsMin: 8,
        repsMax: 12,
        restSeconds: 60,
        notes: 'No swinging. Elbows stay pinned to your sides.',
      },
      {
        id: 'incline_db_curl',
        name: 'Incline Dumbbell Curl',
        muscleGroups: ['biceps'],
        sets: 3,
        repsMin: 10,
        repsMax: 12,
        restSeconds: 60,
        lengthenedPartials: true,
        why: 'Sitting the shoulder behind the body puts the biceps long head at full stretch — the position that drives the most growth and the one standing curls never reach.',
        notes: 'Bench at 45–60°, let the arms hang fully behind you.',
      },
      {
        id: 'pallof_press_wed',
        name: 'Pallof Press',
        muscleGroups: ['core', 'deep_core'],
        sets: 3,
        repsMin: 12,
        repsMax: 15,
        restSeconds: 45,
        perSide: true,
        why: 'This choice is deliberate. Loaded Russian twists and weighted side bends grow the obliques thicker, and thicker obliques are a wider waist — the exact opposite of what you asked for. Pallof presses train the same muscles isometrically for stability without adding width.',
        notes: 'Reps per side. Press straight out and resist the rotation. Do not twist.',
      },
      {
        id: 'suitcase_carry',
        name: 'Suitcase Carry',
        muscleGroups: ['deep_core', 'core'],
        sets: 3,
        repsMin: 40,
        repsMax: 50,
        restSeconds: 60,
        perSide: true,
        isTimed: true,
        why: 'Anti-lateral-flexion. The deep core braces against a load it has to resist rather than move — the same reason it builds trunk stiffness without hypertrophying the obliques for width.',
        notes: 'Metres per side. One heavy dumbbell, walk tall, do not lean away from it.',
      },
    ],
    warmUp: [
      { name: 'Cat-Cow Thoracic Extension', duration: '10 slow reps', description: 'Alternate arching and rounding on hands and knees. Frees the spinal mobility that heavy deadlifting and rowing both demand.' },
      { name: 'Band Pull-Aparts', duration: '20 reps', description: 'Activates the rhomboids, mid-traps and rear delts before heavy pulling. Non-negotiable for shoulder health on pull day.' },
      { name: 'Dead Hang', duration: '3 × 20 secs', description: 'Hang with relaxed shoulders. Decompresses the spine, opens the lats and primes the grip — direct preparation for both the deadlift and the pull-up.' },
      { name: 'Hip Hinge Practice', duration: '10 reps bodyweight', description: 'Feet hip-width, hinge at the hips with a neutral back until you feel hamstring tension, return. Grooves the deadlift pattern under zero load.' },
      { name: 'Ramping Deadlift Sets', duration: '3 ramping sets', description: 'Roughly 40%, 60% and 80% for 3 reps. The deadlift is the heaviest lift of the week — it earns a proper build-up.' },
    ],
    coolDown: [
      { name: 'Child\'s Pose with Lat Reach', duration: '45 secs each side', description: 'Kneel, extend both arms forward, walk the hands to one side. Deep lat stretch that also releases the thoracic extensors after heavy deadlifting.' },
      { name: 'Supine Spinal Twist', duration: '45 secs each side', description: 'Lie on your back, drop both knees to one side, arms out wide. Decompresses the lumbar spine after axial loading.' },
      { name: 'Doorway Lat Stretch', duration: '30 secs each side', description: 'Grip a frame at shoulder height and lean away until the lat lengthens. Particularly valuable after pull-ups and pulldowns.' },
      { name: 'Bicep Wall Stretch', duration: '20 secs each side', description: 'Arm back against a wall at shoulder height, thumb down. Gentle stretch of the biceps and anterior shoulder capsule.' },
    ],
  },

  thursday: null,

  friday: {
    id: 'lower',
    type: 'lower',
    label: 'Legs B — Posterior Chain & Lower Back',
    intent:
      'Second leg day of the week and the second direct lower-back session. Hamstrings, glutes and erectors — the whole back of you, which is the half that was never trained.',
    exercises: [
      {
        id: 'rdl_fri',
        name: 'Romanian Deadlift',
        muscleGroups: ['hamstrings', 'glutes', 'lower_back'],
        sets: 4,
        repsMin: 8,
        repsMax: 10,
        restSeconds: 150,
        compound: true,
        tempo: '4-0-1',
        lengthenedPartials: true,
        why: 'Puts the hamstring under load at its longest, and holds the erectors in a hard isometric for the entire set. Two of this block\'s three priority areas in one movement.',
        notes: 'Hips back, bar dragging the thighs, 4-second lowering. Stop the moment your lower back rounds — that is your range today.',
      },
      {
        id: 'seated_leg_curl_fri',
        name: 'Sliding Leg Curl',
        muscleGroups: ['hamstrings', 'glutes'],
        sets: 3,
        repsMin: 12,
        repsMax: 15,
        restSeconds: 75,
        why: 'Second hamstring session of the week — twice-weekly frequency per muscle beats once for growth. No seated curl machine here, and back-to-back heavy Nordics would wreck recovery, so this is a lighter isolation move that still isolates the knee-flexion function RDL does not.',
        notes: 'On your back, heels on a towel or sliders (or paper plates on carpet), hips lifted. Curl your heels in toward your glutes, then slide them back out under control.',
      },
      {
        id: 'hip_thrust',
        name: 'Barbell Hip Thrust',
        muscleGroups: ['glutes', 'hamstrings'],
        sets: 3,
        repsMin: 10,
        repsMax: 12,
        restSeconds: 90,
        compound: true,
        why: 'The highest glute activation of any loaded movement. Strong glutes also take load off the lower back in every hinge — the two priorities reinforce each other.',
        notes: 'Chin tucked, ribs down, 2-second squeeze at the top. Full lockout every rep.',
        swaps: ['Glute Bridge (barbell)', 'Machine Hip Thrust'],
      },
      {
        id: 'bulgarian_split',
        name: 'Bulgarian Split Squat',
        muscleGroups: ['quads', 'glutes', 'hamstrings'],
        sets: 3,
        repsMin: 10,
        repsMax: 12,
        restSeconds: 90,
        perSide: true,
        why: 'Unilateral quad and glute under a deep stretch, with the rear leg\'s hip flexor lengthening at the same time. Brutal, and the highest return per set on this list.',
        notes: 'Reps per leg. Rear foot elevated, front shin near-vertical, sink deep.',
      },
      {
        id: 'roman_chair_ext',
        name: '90° Roman Chair Back Extension',
        muscleGroups: ['lower_back', 'glutes'],
        sets: 3,
        repsMin: 12,
        repsMax: 15,
        restSeconds: 90,
        why: 'Monday\'s 45° bench is a partial range. The 90° chair takes the spine from full flexion to full extension against gravity — the version that actually builds the erector column. A muscle that has never been trained responds hard to frequency, which is why it gets two sessions.',
        notes: 'Round down segment by segment, extend back to a straight line. Add a plate once bodyweight reps get easy.',
        swaps: ['Reverse Hyperextension', 'Weighted 45° Back Extension'],
      },
      {
        id: 'leg_press_high',
        name: 'Leg Press (feet high and wide)',
        muscleGroups: ['glutes', 'hamstrings', 'quads'],
        sets: 3,
        repsMin: 12,
        repsMax: 15,
        restSeconds: 90,
        why: 'Foot position high on the platform shifts load off the quad and onto the glutes and hamstrings at a deep hip angle — posterior chain volume without more spinal loading after RDLs.',
        notes: 'Feet high and wide, toes slightly out. Full depth, do not let the lower back lift off the pad.',
      },
      {
        id: 'seated_calf',
        name: 'Seated Calf Raise',
        muscleGroups: ['calves'],
        sets: 4,
        repsMin: 15,
        repsMax: 20,
        restSeconds: 60,
        why: 'The soleus only loads with a bent knee, so Monday\'s standing raises miss it entirely. It is also the larger of the two calf muscles by volume.',
        notes: 'Deep stretch at the bottom, 1-second pause at the top.',
      },
      {
        id: 'decline_crunch',
        name: 'Weighted Decline Crunch',
        muscleGroups: ['core'],
        sets: 3,
        repsMin: 12,
        repsMax: 15,
        restSeconds: 60,
        why: 'Loaded spinal flexion at a longer starting range than a floor crunch. Second direct rectus abdominis session of the week — abs respond to frequency and load exactly like any other muscle.',
        notes: 'Hold a plate to the chest. Curl up rib-to-hip, do not just hinge at the hips.',
      },
      {
        id: 'dead_bug',
        name: 'Dead Bug',
        muscleGroups: ['deep_core'],
        sets: 3,
        repsMin: 10,
        repsMax: 12,
        restSeconds: 45,
        perSide: true,
        bodyweight: true,
        why: 'Teaches the deep core to hold a neutral spine while the limbs move — the exact mechanism that stops your lower back arching under a bar. Cheap insurance for everything else in this programme.',
        notes: 'Reps per side. Lower back stays flat on the floor the entire time. If it lifts, shorten the range.',
      },
      {
        id: 'vacuum_fri',
        name: 'Stomach Vacuum',
        muscleGroups: ['deep_core'],
        sets: 3,
        repsMin: 25,
        repsMax: 35,
        restSeconds: 45,
        bodyweight: true,
        isTimed: true,
        why: 'Second transverse abdominis session. This is the muscle that determines how far your midsection sits in at any given body fat — the corset under the abs.',
        notes: 'Seconds held. Full exhale, navel to spine, hold without breathing in.',
      },
    ],
    warmUp: [
      { name: 'Hip Circles', duration: '10 reps each direction', description: 'Large knee circles standing on one foot. Mobilises the hip capsule before heavy RDLs and hip thrusts.' },
      { name: 'Glute Bridges', duration: '20 reps', description: 'Hard squeeze at the top of each rep. Activates the glutes so the hamstrings and erectors do not over-compensate under load.' },
      { name: 'Banded Clamshells', duration: '15 reps each side', description: 'Side-lying, band above the knees, open the top knee. Fires the gluteus medius, which stabilises the pelvis through every split squat rep.' },
      { name: 'Cat-Cow', duration: '10 slow reps', description: 'Takes the erector spinae through full flexion and extension unloaded before the Roman chair asks for the same range under load.' },
      { name: 'Bodyweight Hip Hinge', duration: '15 reps', description: 'Hinge to hamstring tension with a neutral back. Sets the RDL groove before the bar is in your hands.' },
    ],
    coolDown: [
      { name: 'Supine Hamstring Stretch', duration: '45 secs each side', description: 'Pull one straight leg toward the chest. The hamstrings take the most volume today — static stretching restores their resting length and reduces DOMS.' },
      { name: 'Pigeon Pose', duration: '60 secs each side', description: 'Shin across the mat, opposite leg back, sink the hips. The deepest available stretch for the piriformis and glute complex after hip thrusts and split squats.' },
      { name: 'Kneeling Hip Flexor Stretch', duration: '45 secs each side', description: 'Rear knee down, push the hips forward. RDLs lengthen the hamstrings but leave the hip flexors contracted throughout — this counterbalances it.' },
      { name: 'Child\'s Pose', duration: '60 secs', description: 'Sit back on the heels, arms extended. Decompresses the lumbar spine after two direct erector movements plus heavy hinging.' },
      { name: 'Seated Butterfly Stretch', duration: '45 secs', description: 'Soles together, let the knees fall out, lean forward gently. Stretches the adductors after wide-stance leg press.' },
    ],
  },

  saturday: {
    id: 'upper',
    type: 'upper',
    label: 'Upper — Detail, Taper & Deep Core',
    intent:
      'Second chest and back session at different angles, plus the delt volume that builds the taper. Lighter loads, tighter form, higher reps — this is the finishing session, not a max-effort day.',
    exercises: [
      {
        id: 'incline_bb_press',
        name: 'Incline Barbell Press',
        muscleGroups: ['chest', 'shoulders'],
        sets: 4,
        repsMin: 8,
        repsMax: 10,
        restSeconds: 150,
        compound: true,
        why: 'Second upper-chest session of the week at a different angle to Tuesday. Chest is a stated growth priority, so it gets two dedicated hits and both start with it — 15–30° changes in bench angle measurably shift where peak activation lands.',
        notes: 'Bench at 30°. Touch high on the chest, just below the collarbone.',
      },
      {
        id: 'pullups_sat',
        name: 'Weighted Pull-Up',
        muscleGroups: ['back', 'biceps'],
        sets: 4,
        repsMin: 8,
        repsMax: 12,
        restSeconds: 120,
        compound: true,
        notes: 'Lighter than Wednesday, higher reps. Full dead hang each rep.',
        swaps: ['Lat Pulldown', 'Assisted Pull-Up'],
      },
      {
        id: 'pec_deck',
        name: 'Pec Deck / Machine Fly',
        muscleGroups: ['chest'],
        sets: 3,
        repsMin: 12,
        repsMax: 15,
        restSeconds: 60,
        lengthenedPartials: true,
        why: 'Elbows fixed means the pec does all the work through a clean arc — the peak-contraction end of the chest that presses under-stimulate.',
        notes: 'Hold the squeeze 1 second. Last set: partials from the stretched position after failure.',
      },
      {
        id: 'tbar_row',
        name: 'T-Bar Row',
        muscleGroups: ['back'],
        sets: 3,
        repsMin: 10,
        repsMax: 12,
        restSeconds: 90,
        compound: true,
        why: 'Second back-thickness angle of the week. A neutral close grip pulls the mid-back and lower lats harder than the wide grip used on Wednesday.',
        notes: 'Chest up, pull to the sternum, control the negative.',
      },
      {
        id: 'cable_lateral',
        name: 'Cable Lateral Raise',
        muscleGroups: ['shoulders'],
        sets: 3,
        repsMin: 15,
        repsMax: 20,
        restSeconds: 45,
        why: 'A cable keeps tension on the delt at the bottom, where a dumbbell has almost none. Second delt session of the week because shoulder width is doing real work for your taper.',
        notes: 'One arm at a time, cable behind you, lead with the elbow.',
      },
      {
        id: 'rear_delt_fly',
        name: 'Reverse Pec Deck / Rear Delt Fly',
        muscleGroups: ['shoulders', 'back'],
        sets: 3,
        repsMin: 15,
        repsMax: 20,
        restSeconds: 45,
        why: 'Rear delts round the shoulder out from the side and pull your posture back — the difference between wide shoulders and a wide, upright frame.',
      },
      {
        id: 'skull_crushers',
        name: 'EZ-Bar Skull Crusher',
        muscleGroups: ['triceps'],
        sets: 3,
        repsMin: 10,
        repsMax: 12,
        restSeconds: 60,
        notes: 'Lower behind the head, not to the forehead — keeps the long head loaded through the stretch.',
      },
      {
        id: 'hammer_curl',
        name: 'Hammer Curl',
        muscleGroups: ['biceps'],
        sets: 3,
        repsMin: 10,
        repsMax: 12,
        restSeconds: 60,
        why: 'The brachialis sits underneath the biceps and pushes it up as it grows. This is arm thickness, not arm peak — and it fills the gap between biceps and triceps from the side.',
      },
      {
        id: 'ab_wheel_sat',
        name: 'Ab Wheel Rollout',
        muscleGroups: ['core', 'deep_core'],
        sets: 3,
        repsMin: 8,
        repsMax: 12,
        restSeconds: 60,
        bodyweight: true,
        why: 'The hardest anti-extension movement available — the rectus abdominis and the deep core resisting the spine being pulled into extension under a long lever.',
        notes: 'Stop the instant your lower back starts to arch. That point is your honest current range — extend it week by week.',
      },
      {
        id: 'side_plank_sat',
        name: 'Side Plank',
        muscleGroups: ['deep_core'],
        sets: 3,
        repsMin: 45,
        repsMax: 60,
        restSeconds: 45,
        perSide: true,
        bodyweight: true,
        isTimed: true,
        why: 'Isometric, deliberately. It builds oblique bracing capacity without the loaded lateral flexion — side bends, weighted twists, hip dips — that thickens the obliques and widens the waist.',
        notes: 'Seconds per side. Body in a straight line, hips high, do not let them sag.',
      },
    ],
    warmUp: [
      { name: 'Thoracic Extension on Foam Roller', duration: '10 slow passes', description: 'Roller under the mid-back, extend gently over it at several segments. Undoes desk posture and opens the thoracic spine before incline pressing.' },
      { name: 'Shoulder 90/90 External Rotation', duration: '10 reps each side', description: 'Upper arm parallel to the floor, elbow at 90°, rotate the forearm up and down. Primes the rotator cuff — critical on the fourth pressing exposure of the week.' },
      { name: 'Dead Hang', duration: '3 × 20 secs', description: 'Decompresses the spine and opens the lats and shoulder capsule after a week that included deadlifts, RDLs and two back-extension sessions.' },
      { name: 'Band Pull-Aparts', duration: '20 reps', description: 'Activates rear delts, rhomboids and lower traps — the scapular stabilisers underpinning everything in this session.' },
      { name: 'Scapular Push-Ups', duration: '15 reps', description: 'Serratus activation. Keeps the shoulder blade tracking correctly through pressing and pulling volume.' },
    ],
    coolDown: [
      { name: 'Doorway Chest Stretch', duration: '45 secs each side', description: 'Restores pec minor and anterior deltoid length after the week\'s total pressing volume.' },
      { name: 'Child\'s Pose with Lat Reach', duration: '45 secs each side', description: 'Decompresses the thoracic spine and stretches the lats after pulling work.' },
      { name: 'Cross-Body Shoulder Stretch', duration: '30 secs each side', description: 'Releases the posterior shoulder capsule — tightness here is a leading contributor to shoulder injury in high-volume pressing blocks.' },
      { name: 'Wrist Flexor/Extensor Stretch', duration: '20 secs each direction per wrist', description: 'Arm extended, bend the wrist up then down with the opposite hand. Forearm health underpins long-term pressing, curling and carrying capacity.' },
      { name: 'Full Body Reset Breathing', duration: '2 mins', description: 'Lie on your back, knees bent, hand on the stomach. Slow nasal inhale, long exhale. Shifts you out of sympathetic drive after five training days — recovery starts here, not at bedtime.' },
    ],
  },

  sunday: null,
};

export const SESSION_LABELS: Record<string, string> = {
  push: 'Push',
  pull: 'Pull',
  legs: 'Legs A',
  upper: 'Upper',
  lower: 'Legs B',
  rest: 'Rest',
};

export const SESSION_COLORS: Record<string, string> = {
  push: '#2d9cff',
  pull: '#8b5cf6',
  legs: '#22c55e',
  upper: '#f59e0b',
  lower: '#ef4444',
  rest: '#4a5568',
};

/** Weekly set counts per priority area, for the "why this split" panel. */
export const WEEKLY_VOLUME_SUMMARY: readonly { area: string; sets: number; note: string }[] = [
  { area: 'Quads', sets: 13, note: 'Squat, hack squat, lunge, leg extension — was 13 unfocused sets, now front-loaded on Monday' },
  { area: 'Hamstrings', sets: 15, note: 'Nordic and sliding curls twice weekly, plus RDL and leg press' },
  { area: 'Glutes', sets: 12, note: 'Hip thrust, split squat, high-foot leg press, back extensions' },
  { area: 'Lower back', sets: 7, note: 'Was 0 direct sets. Now 45° extensions, Roman chair, plus heavy hinging' },
  { area: 'Chest', sets: 14, note: 'Three angles on Tuesday, two on Saturday — upper chest leads both sessions' },
  { area: 'Abs (rectus)', sets: 12, note: 'Loaded crunches twice weekly, hanging raises, ab wheel' },
  { area: 'Deep core / TVA', sets: 12, note: 'Vacuums, Pallof, carries, dead bugs, side planks — all waist-narrowing, none waist-widening' },
  { area: 'Delts (side)', sets: 7, note: 'Width you can build during a deficit — half of the taper equation' },
];
