import type { WorkoutSession, DayOfWeek } from '../types';

export const WEEKLY_SPLIT: Record<DayOfWeek, WorkoutSession | null> = {
  monday: {
    id: 'push',
    type: 'push',
    label: 'Push — Chest Primary',
    exercises: [
      {
        id: 'bench_press',
        name: 'Barbell Bench Press',
        muscleGroups: ['chest', 'shoulders', 'triceps'],
        sets: 4,
        repsMin: 6,
        repsMax: 8,
        restSeconds: 150,
        notes: 'Log weight every session — primary strength movement',
      },
      {
        id: 'incline_db_press',
        name: 'Incline Dumbbell Press',
        muscleGroups: ['chest', 'shoulders'],
        sets: 3,
        repsMin: 10,
        repsMax: 12,
        restSeconds: 90,
        notes: 'Upper chest emphasis',
      },
      {
        id: 'cable_fly',
        name: 'Cable Chest Fly',
        muscleGroups: ['chest'],
        sets: 3,
        repsMin: 12,
        repsMax: 15,
        restSeconds: 60,
        notes: 'Full stretch at bottom',
      },
      {
        id: 'ohp_mon',
        name: 'Overhead Press',
        muscleGroups: ['shoulders', 'triceps'],
        sets: 3,
        repsMin: 8,
        repsMax: 10,
        restSeconds: 120,
        notes: 'Strict form — no leg drive',
      },
      {
        id: 'lateral_raises_mon',
        name: 'Lateral Raises',
        muscleGroups: ['shoulders'],
        sets: 4,
        repsMin: 12,
        repsMax: 15,
        restSeconds: 60,
        notes: 'Slow 3-sec eccentric — no swinging',
      },
      {
        id: 'rope_pushdown',
        name: 'Tricep Rope Pushdown',
        muscleGroups: ['triceps'],
        sets: 3,
        repsMin: 12,
        repsMax: 15,
        restSeconds: 60,
      },
      {
        id: 'oh_tricep_ext',
        name: 'Overhead Tricep Extension',
        muscleGroups: ['triceps'],
        sets: 3,
        repsMin: 10,
        repsMax: 12,
        restSeconds: 60,
        notes: 'Long head emphasis',
      },
    ],
  },

  tuesday: {
    id: 'pull',
    type: 'pull',
    label: 'Pull — Back Thickness',
    exercises: [
      {
        id: 'deadlift',
        name: 'Conventional Deadlift',
        muscleGroups: ['back', 'hamstrings', 'glutes'],
        sets: 4,
        repsMin: 5,
        repsMax: 6,
        restSeconds: 180,
        notes: 'Heaviest compound of the week — brace hard',
      },
      {
        id: 'barbell_row',
        name: 'Barbell Row (Overhand)',
        muscleGroups: ['back'],
        sets: 4,
        repsMin: 8,
        repsMax: 10,
        restSeconds: 120,
        notes: 'Chest to pad, strict form',
      },
      {
        id: 'cable_row',
        name: 'Seated Cable Row',
        muscleGroups: ['back'],
        sets: 3,
        repsMin: 10,
        repsMax: 12,
        restSeconds: 90,
        notes: 'Close grip',
      },
      {
        id: 'lat_pulldown',
        name: 'Lat Pulldown (Wide Grip)',
        muscleGroups: ['back'],
        sets: 3,
        repsMin: 10,
        repsMax: 12,
        restSeconds: 90,
      },
      {
        id: 'face_pulls',
        name: 'Face Pulls',
        muscleGroups: ['shoulders', 'back'],
        sets: 3,
        repsMin: 15,
        repsMax: 20,
        restSeconds: 60,
        notes: 'Non-negotiable for shoulder health',
      },
      {
        id: 'bb_curl',
        name: 'Barbell Curl',
        muscleGroups: ['biceps'],
        sets: 3,
        repsMin: 10,
        repsMax: 12,
        restSeconds: 60,
      },
      {
        id: 'hammer_curl',
        name: 'Hammer Curl',
        muscleGroups: ['biceps'],
        sets: 3,
        repsMin: 10,
        repsMax: 12,
        restSeconds: 60,
        notes: 'Brachialis + forearm',
      },
    ],
  },

  wednesday: {
    id: 'legs',
    type: 'legs',
    label: 'Legs — Quad Primary',
    exercises: [
      {
        id: 'back_squat',
        name: 'Barbell Back Squat',
        muscleGroups: ['quads', 'glutes', 'hamstrings'],
        sets: 4,
        repsMin: 6,
        repsMax: 8,
        restSeconds: 180,
        notes: 'King of all movements — depth matters',
      },
      {
        id: 'leg_press',
        name: 'Leg Press',
        muscleGroups: ['quads', 'glutes'],
        sets: 3,
        repsMin: 12,
        repsMax: 15,
        restSeconds: 120,
        notes: 'Feet shoulder-width, full ROM',
      },
      {
        id: 'hack_squat',
        name: 'Hack Squat',
        muscleGroups: ['quads'],
        sets: 3,
        repsMin: 10,
        repsMax: 12,
        restSeconds: 90,
        notes: 'Quad isolation',
      },
      {
        id: 'leg_ext',
        name: 'Leg Extension',
        muscleGroups: ['quads'],
        sets: 3,
        repsMin: 12,
        repsMax: 15,
        restSeconds: 60,
        notes: 'End-range contraction — hold 1 sec',
      },
      {
        id: 'rdl_wed',
        name: 'Romanian Deadlift',
        muscleGroups: ['hamstrings', 'glutes'],
        sets: 3,
        repsMin: 10,
        repsMax: 12,
        restSeconds: 120,
        notes: 'Hamstring stretch — feel it, control it',
      },
      {
        id: 'leg_curl_wed',
        name: 'Lying Leg Curl',
        muscleGroups: ['hamstrings'],
        sets: 3,
        repsMin: 12,
        repsMax: 15,
        restSeconds: 60,
      },
      {
        id: 'standing_calf',
        name: 'Standing Calf Raise',
        muscleGroups: ['calves'],
        sets: 4,
        repsMin: 15,
        repsMax: 20,
        restSeconds: 60,
        notes: 'Full stretch at bottom every rep',
      },
      {
        id: 'cable_crunch_wed',
        name: 'Cable Crunch',
        muscleGroups: ['core'],
        sets: 3,
        repsMin: 15,
        repsMax: 20,
        restSeconds: 60,
      },
      {
        id: 'plank_wed',
        name: 'Plank',
        muscleGroups: ['core'],
        sets: 3,
        repsMin: 45,
        repsMax: 60,
        restSeconds: 60,
        notes: 'Seconds — squeeze everything',
      },
    ],
  },

  thursday: null,

  friday: {
    id: 'upper',
    type: 'upper',
    label: 'Upper — Compound Re-Stimulus',
    exercises: [
      {
        id: 'ohp_fri',
        name: 'Overhead Press (BB)',
        muscleGroups: ['shoulders', 'triceps'],
        sets: 4,
        repsMin: 6,
        repsMax: 8,
        restSeconds: 150,
        notes: 'Shoulder-primary today — different emphasis to Monday',
      },
      {
        id: 'weighted_pullups',
        name: 'Weighted Pull-ups',
        muscleGroups: ['back', 'biceps'],
        sets: 4,
        repsMin: 6,
        repsMax: 10,
        restSeconds: 150,
        notes: 'Add weight if you can do 10+ clean reps',
      },
      {
        id: 'incline_bb_press',
        name: 'Incline Barbell Press',
        muscleGroups: ['chest', 'shoulders'],
        sets: 3,
        repsMin: 8,
        repsMax: 10,
        restSeconds: 120,
        notes: 'Upper chest angle — different to Monday flat',
      },
      {
        id: 'tbar_row',
        name: 'T-Bar Row',
        muscleGroups: ['back'],
        sets: 3,
        repsMin: 10,
        repsMax: 12,
        restSeconds: 90,
        notes: 'Mid-back thickness',
      },
      {
        id: 'lateral_raises_fri',
        name: 'Lateral Raises',
        muscleGroups: ['shoulders'],
        sets: 3,
        repsMin: 15,
        repsMax: 20,
        restSeconds: 60,
        notes: 'High rep — shoulder width',
      },
      {
        id: 'rear_delt_fly',
        name: 'Rear Delt Fly',
        muscleGroups: ['shoulders', 'back'],
        sets: 3,
        repsMin: 15,
        repsMax: 20,
        restSeconds: 60,
        notes: 'Posture + rear delt',
      },
      {
        id: 'skull_crushers',
        name: 'Skull Crushers (EZ Bar)',
        muscleGroups: ['triceps'],
        sets: 3,
        repsMin: 10,
        repsMax: 12,
        restSeconds: 60,
      },
      {
        id: 'incline_db_curl',
        name: 'Incline Dumbbell Curl',
        muscleGroups: ['biceps'],
        sets: 3,
        repsMin: 10,
        repsMax: 12,
        restSeconds: 60,
        notes: 'Long head stretch',
      },
    ],
  },

  saturday: {
    id: 'lower',
    type: 'lower',
    label: 'Lower — Posterior Chain',
    exercises: [
      {
        id: 'rdl_sat',
        name: 'Romanian Deadlift',
        muscleGroups: ['hamstrings', 'glutes', 'back'],
        sets: 4,
        repsMin: 8,
        repsMax: 10,
        restSeconds: 150,
        notes: 'Heaviest RDL of the week',
      },
      {
        id: 'bulgarian_split',
        name: 'Bulgarian Split Squat',
        muscleGroups: ['quads', 'glutes', 'hamstrings'],
        sets: 3,
        repsMin: 10,
        repsMax: 12,
        restSeconds: 120,
        notes: 'Each leg — use DBs for balance first',
      },
      {
        id: 'leg_press_high',
        name: 'Leg Press (Feet High + Wide)',
        muscleGroups: ['glutes', 'hamstrings', 'quads'],
        sets: 3,
        repsMin: 12,
        repsMax: 15,
        restSeconds: 120,
        notes: 'Glute + hamstring emphasis',
      },
      {
        id: 'leg_curl_sat',
        name: 'Lying Leg Curl',
        muscleGroups: ['hamstrings'],
        sets: 4,
        repsMin: 10,
        repsMax: 12,
        restSeconds: 60,
      },
      {
        id: 'hip_thrust',
        name: 'Hip Thrust (Barbell)',
        muscleGroups: ['glutes', 'hamstrings'],
        sets: 3,
        repsMin: 12,
        repsMax: 15,
        restSeconds: 90,
        notes: 'Maximum glute activation — squeeze at top',
      },
      {
        id: 'seated_calf',
        name: 'Seated Calf Raise',
        muscleGroups: ['calves'],
        sets: 4,
        repsMin: 15,
        repsMax: 20,
        restSeconds: 60,
        notes: 'Soleus emphasis',
      },
      {
        id: 'hanging_leg_raise',
        name: 'Hanging Leg Raise',
        muscleGroups: ['core'],
        sets: 3,
        repsMin: 12,
        repsMax: 15,
        restSeconds: 60,
        notes: 'Lower abs',
      },
      {
        id: 'cable_crunch_sat',
        name: 'Cable Crunch',
        muscleGroups: ['core'],
        sets: 3,
        repsMin: 15,
        repsMax: 20,
        restSeconds: 60,
      },
    ],
  },

  sunday: null,
};

export const SESSION_LABELS: Record<string, string> = {
  push: 'Push',
  pull: 'Pull',
  legs: 'Legs',
  upper: 'Upper',
  lower: 'Lower',
  rest: 'Rest',
};

export const SESSION_COLORS: Record<string, string> = {
  push: '#3b82f6',
  pull: '#8b5cf6',
  legs: '#22c55e',
  upper: '#f59e0b',
  lower: '#ef4444',
  rest: '#555555',
};
