import type { WorkoutSession, DayOfWeek } from '../types';

export const WEEKLY_SPLIT: Record<DayOfWeek, WorkoutSession | null> = {
  monday: {
    id: 'push',
    type: 'push',
    label: 'Push — Chest Primary',
    exercises: [
      {
        id: 'bench_press',
        name: 'Barbell Bench Press',
        muscleGroups: ['chest', 'shoulders', 'triceps'],
        sets: 4,
        repsMin: 6,
        repsMax: 8,
        restSeconds: 150,
        notes: 'Log weight every session — primary strength movement',
      },
      {
        id: 'incline_db_press',
        name: 'Incline Dumbbell Press',
        muscleGroups: ['chest', 'shoulders'],
        sets: 3,
        repsMin: 10,
        repsMax: 12,
        restSeconds: 90,
        notes: 'Upper chest emphasis',
      },
      {
        id: 'cable_fly',
        name: 'Cable Chest Fly',
        muscleGroups: ['chest'],
        sets: 3,
        repsMin: 12,
        repsMax: 15,
        restSeconds: 60,
        notes: 'Full stretch at bottom',
      },
      {
        id: 'ohp_mon',
        name: 'Overhead Press',
        muscleGroups: ['shoulders', 'triceps'],
        sets: 3,
        repsMin: 8,
        repsMax: 10,
        restSeconds: 120,
        notes: 'Strict form — no leg drive',
      },
      {
        id: 'lateral_raises_mon',
        name: 'Lateral Raises',
        muscleGroups: ['shoulders'],
        sets: 4,
        repsMin: 12,
        repsMax: 15,
        restSeconds: 60,
        notes: 'Slow 3-sec eccentric — no swinging',
      },
      {
        id: 'rope_pushdown',
        name: 'Tricep Rope Pushdown',
        muscleGroups: ['triceps'],
        sets: 3,
        repsMin: 12,
        repsMax: 15,
        restSeconds: 60,
      },
      {
        id: 'oh_tricep_ext',
        name: 'Overhead Tricep Extension',
        muscleGroups: ['triceps'],
        sets: 3,
        repsMin: 10,
        repsMax: 12,
        restSeconds: 60,
        notes: 'Long head emphasis',
      },
    ],
    warmUp: [
      { name: 'Arm Circles', duration: '30 secs each direction', description: 'Arms out to sides, large circles forward then backward. Mobilises the shoulder joint and warms rotator cuff before any pressing load.' },
      { name: 'Band Pull-Aparts', duration: '20 reps', description: 'Hold a band or towel at shoulder width, arms straight. Pull apart toward chest. Activates rear delts and opens the anterior shoulder — cuts impingement risk on bench and OHP.' },
      { name: 'Doorway Chest Opener', duration: '30 secs each side', description: 'Forearm on doorframe at 90°, elbow at shoulder height. Lean gently through. Increases pec minor flexibility and anterior shoulder range before loading.' },
      { name: 'Scapular Push-Ups', duration: '15 reps', description: 'Plank position. Protract and retract shoulder blades without bending elbows. Activates serratus anterior, which stabilises the scapula through every press rep.' },
      { name: 'Light Warm-Up Press', duration: '2 × 15 reps (empty bar or very light)', description: 'Two sets at minimal weight. Primes the neuromuscular pattern, lubricates the elbow and shoulder joints before loading.' },
    ],
    coolDown: [
      { name: 'Doorway Chest Stretch (held)', duration: '45 secs each side', description: 'Same as warm-up position but hold longer. Passive static stretching post-training restores resting pec length and reduces next-day tightness.' },
      { name: 'Cross-Body Shoulder Stretch', duration: '30 secs each side', description: 'Pull one straight arm across your chest. Hold at mild tension in rear delt and lateral shoulder capsule.' },
      { name: 'Overhead Tricep Stretch', duration: '30 secs each side', description: 'Arm overhead, elbow bent, hand behind head. Press elbow down gently with opposite hand. Stretches the long head — most loaded during overhead movements.' },
      { name: 'Lying Pec Stretch', duration: '45 secs each side', description: 'Face down, one arm extended sideways at shoulder height. Roll gently onto that side. Deep stretch of the sternal pec head.' },
    ],
  },

  tuesday: {
    id: 'pull',
    type: 'pull',
    label: 'Pull — Back Thickness',
    exercises: [
      {
        id: 'deadlift',
        name: 'Conventional Deadlift',
        muscleGroups: ['back', 'hamstrings', 'glutes'],
        sets: 4,
        repsMin: 5,
        repsMax: 6,
        restSeconds: 180,
        notes: 'Heaviest compound of the week — brace hard',
      },
      {
        id: 'barbell_row',
        name: 'Barbell Row (Overhand)',
        muscleGroups: ['back'],
        sets: 4,
        repsMin: 8,
        repsMax: 10,
        restSeconds: 120,
        notes: 'Chest to pad, strict form',
      },
      {
        id: 'cable_row',
        name: 'Seated Cable Row',
        muscleGroups: ['back'],
        sets: 3,
        repsMin: 10,
        repsMax: 12,
        restSeconds: 90,
        notes: 'Close grip',
      },
      {
        id: 'lat_pulldown',
        name: 'Lat Pulldown (Wide Grip)',
        muscleGroups: ['back'],
        sets: 3,
        repsMin: 10,
        repsMax: 12,
        restSeconds: 90,
      },
      {
        id: 'face_pulls',
        name: 'Face Pulls',
        muscleGroups: ['shoulders', 'back'],
        sets: 3,
        repsMin: 15,
        repsMax: 20,
        restSeconds: 60,
        notes: 'Non-negotiable for shoulder health',
      },
      {
        id: 'bb_curl',
        name: 'Barbell Curl',
        muscleGroups: ['biceps'],
        sets: 3,
        repsMin: 10,
        repsMax: 12,
        restSeconds: 60,
      },
      {
        id: 'hammer_curl',
        name: 'Hammer Curl',
        muscleGroups: ['biceps'],
        sets: 3,
        repsMin: 10,
        repsMax: 12,
        restSeconds: 60,
        notes: 'Brachialis + forearm',
      },
    ],
    warmUp: [
      { name: 'Cat-Cow Thoracic Extension', duration: '10 slow reps', description: 'On hands and knees, alternate between arching and rounding the thoracic spine. Frees up spinal mobility required for deadlifting and rowing.' },
      { name: 'Band Pull-Aparts', duration: '20 reps', description: 'Activates the scapular retractors (rhomboids, mid-traps, rear delts) before heavy pulling. Non-negotiable for shoulder health on pull day.' },
      { name: 'Dead Hang', duration: '3 × 20 secs', description: 'Hang from a pull-up bar with relaxed shoulders. Decompresses the spine, opens the lats, and primes the grip. Direct prep for deadlifts and pull-ups.' },
      { name: 'Hip Hinge Practice', duration: '10 reps (bodyweight)', description: 'Stand with feet hip-width, hinge at hips keeping back neutral, push hips back until you feel hamstring tension, return. Grooves the deadlift pattern under zero load.' },
      { name: 'Lat Overhead Stretch', duration: '20 secs each side', description: 'Reach one arm overhead and side-bend away. Decompresses the lat and thoracolumbar fascia before row and pulldown movements.' },
    ],
    coolDown: [
      { name: 'Child\'s Pose with Lat Reach', duration: '45 secs each side', description: 'Kneel, sit back on heels, extend both arms forward on floor. Walk hands to one side. Deep lat stretch that also releases the thoracic extensors strained during deadlifts.' },
      { name: 'Thoracic Rotation Stretch', duration: '30 secs each side', description: 'Seated or kneeling. Place one hand behind your head, rotate your upper body to that side. Restores thoracic rotation compressed during heavy rows.' },
      { name: 'Bicep Wall Stretch', duration: '20 secs each side', description: 'Extend arm back behind you at shoulder height against a wall, thumb pointing down. Gentle stretch of the bicep and anterior shoulder capsule.' },
      { name: 'Doorway Lat Stretch', duration: '30 secs each side', description: 'Grip a doorframe at shoulder height with one hand. Lean away until you feel the lat stretch through the side. Particularly valuable after lat pulldowns.' },
    ],
  },

  wednesday: {
    id: 'legs',
    type: 'legs',
    label: 'Legs — Quad Primary',
    exercises: [
      {
        id: 'back_squat',
        name: 'Barbell Back Squat',
        muscleGroups: ['quads', 'glutes', 'hamstrings'],
        sets: 4,
        repsMin: 6,
        repsMax: 8,
        restSeconds: 180,
        notes: 'King of all movements — depth matters',
      },
      {
        id: 'leg_press',
        name: 'Leg Press',
        muscleGroups: ['quads', 'glutes'],
        sets: 3,
        repsMin: 12,
        repsMax: 15,
        restSeconds: 120,
        notes: 'Feet shoulder-width, full ROM',
      },
      {
        id: 'hack_squat',
        name: 'Hack Squat',
        muscleGroups: ['quads'],
        sets: 3,
        repsMin: 10,
        repsMax: 12,
        restSeconds: 90,
        notes: 'Quad isolation',
      },
      {
        id: 'leg_ext',
        name: 'Leg Extension',
        muscleGroups: ['quads'],
        sets: 3,
        repsMin: 12,
        repsMax: 15,
        restSeconds: 60,
        notes: 'End-range contraction — hold 1 sec',
      },
      {
        id: 'rdl_wed',
        name: 'Romanian Deadlift',
        muscleGroups: ['hamstrings', 'glutes'],
        sets: 3,
        repsMin: 10,
        repsMax: 12,
        restSeconds: 120,
        notes: 'Hamstring stretch — feel it, control it',
      },
      {
        id: 'leg_curl_wed',
        name: 'Lying Leg Curl',
        muscleGroups: ['hamstrings'],
        sets: 3,
        repsMin: 12,
        repsMax: 15,
        restSeconds: 60,
      },
      {
        id: 'standing_calf',
        name: 'Standing Calf Raise',
        muscleGroups: ['calves'],
        sets: 4,
        repsMin: 15,
        repsMax: 20,
        restSeconds: 60,
        notes: 'Full stretch at bottom every rep',
      },
      {
        id: 'cable_crunch_wed',
        name: 'Cable Crunch',
        muscleGroups: ['core'],
        sets: 3,
        repsMin: 15,
        repsMax: 20,
        restSeconds: 60,
      },
      {
        id: 'plank_wed',
        name: 'Plank',
        muscleGroups: ['core'],
        sets: 3,
        repsMin: 45,
        repsMax: 60,
        restSeconds: 60,
        notes: 'Seconds — squeeze everything',
      },
    ],
    warmUp: [
      { name: 'Hip Circles', duration: '10 reps each direction', description: 'Stand on one foot, draw large circles with the raised knee. Mobilises the hip joint in all planes before squatting. Reduces femoral impingement at depth.' },
      { name: 'Leg Swings', duration: '10 reps each direction per leg', description: 'Hold a wall for balance. Swing one leg forward and back, then side to side. Dynamic stretch that warms the hip flexors, hamstrings and adductors before loaded movement.' },
      { name: 'Deep Bodyweight Squat Hold', duration: '3 × 30 secs', description: 'Sink into the bottom of a squat and hold. Heels flat, knees tracking toes. Identifies mobility restrictions before loading and opens up hip flexors and ankles.' },
      { name: 'Hip Flexor Kneeling Lunge', duration: '30 secs each side', description: 'Rear knee on floor, front foot flat. Push hips forward gently. Tight hip flexors cause anterior pelvic tilt under the bar — this directly addresses that.' },
      { name: 'Glute Bridges', duration: '20 reps slow', description: 'Lying on back, feet flat, drive hips up squeezing glutes at the top. Activates the posterior chain before squats — particularly important if you\'ve been sitting.' },
    ],
    coolDown: [
      { name: 'Standing Quad Stretch', duration: '45 secs each side', description: 'Stand on one leg, pull the other foot to your glute. Hold at the point of quad tension. The quads are heavily loaded on leg day — restoring their resting length reduces DOMS.' },
      { name: 'Supine Hamstring Stretch', duration: '45 secs each side', description: 'Lie on back, pull one leg toward your chest keeping it as straight as possible. The hamstrings act as decelerators during squats and are often undertreated post-training.' },
      { name: 'Pigeon Pose (Figure-4)', duration: '60 secs each side', description: 'Lying on back, cross one ankle over the opposite knee. Pull both legs toward chest. Deeply stretches the piriformis and gluteus medius — the hip rotators compressed during heavy squatting.' },
      { name: 'Standing Calf Stretch', duration: '30 secs each side', description: 'Foot flat on floor, lean into a wall with a straight knee. Restricted ankle dorsiflexion limits squat depth and shifts load to the knee — this directly addresses that.' },
      { name: 'Hip Flexor Lunge Stretch (held)', duration: '45 secs each side', description: 'Same as warm-up but held longer. Counteracts the hip flexor shortening caused by heavy squat loading, especially important for posture.' },
    ],
  },

  thursday: null,

  friday: {
    id: 'upper',
    type: 'upper',
    label: 'Upper — Compound Re-Stimulus',
    exercises: [
      {
        id: 'ohp_fri',
        name: 'Overhead Press (BB)',
        muscleGroups: ['shoulders', 'triceps'],
        sets: 4,
        repsMin: 6,
        repsMax: 8,
        restSeconds: 150,
        notes: 'Shoulder-primary today — different emphasis to Monday',
      },
      {
        id: 'weighted_pullups',
        name: 'Weighted Pull-ups',
        muscleGroups: ['back', 'biceps'],
        sets: 4,
        repsMin: 6,
        repsMax: 10,
        restSeconds: 150,
        notes: 'Add weight if you can do 10+ clean reps',
      },
      {
        id: 'incline_bb_press',
        name: 'Incline Barbell Press',
        muscleGroups: ['chest', 'shoulders'],
        sets: 3,
        repsMin: 8,
        repsMax: 10,
        restSeconds: 120,
        notes: 'Upper chest angle — different to Monday flat',
      },
      {
        id: 'tbar_row',
        name: 'T-Bar Row',
        muscleGroups: ['back'],
        sets: 3,
        repsMin: 10,
        repsMax: 12,
        restSeconds: 90,
        notes: 'Mid-back thickness',
      },
      {
        id: 'lateral_raises_fri',
        name: 'Lateral Raises',
        muscleGroups: ['shoulders'],
        sets: 3,
        repsMin: 15,
        repsMax: 20,
        restSeconds: 60,
        notes: 'High rep — shoulder width',
      },
      {
        id: 'rear_delt_fly',
        name: 'Rear Delt Fly',
        muscleGroups: ['shoulders', 'back'],
        sets: 3,
        repsMin: 15,
        repsMax: 20,
        restSeconds: 60,
        notes: 'Posture + rear delt',
      },
      {
        id: 'skull_crushers',
        name: 'Skull Crushers (EZ Bar)',
        muscleGroups: ['triceps'],
        sets: 3,
        repsMin: 10,
        repsMax: 12,
        restSeconds: 60,
      },
      {
        id: 'incline_db_curl',
        name: 'Incline Dumbbell Curl',
        muscleGroups: ['biceps'],
        sets: 3,
        repsMin: 10,
        repsMax: 12,
        restSeconds: 60,
        notes: 'Long head stretch',
      },
    ],
    warmUp: [
      { name: 'Thoracic Extension on Foam Roller', duration: '10 slow passes', description: 'Place foam roller under mid-back. Support your head and gently extend over the roller at different thoracic segments. Undoes desk posture and opens the thoracic spine before overhead pressing.' },
      { name: 'Shoulder 90/90 External Rotation', duration: '10 reps each side', description: 'Upper arm parallel to floor, elbow bent 90°. Rotate forearm up and down against resistance. Activates the rotator cuff muscles critical for shoulder stability during OHP and pull-ups.' },
      { name: 'Dead Hangs', duration: '3 × 20 secs', description: 'Hang relaxed from pull-up bar. Decompresses the spine, opens the lats and shoulder capsule. Essential warm-up before weighted pull-ups.' },
      { name: 'Band Pull-Aparts', duration: '20 reps', description: 'Activates rear delts, rhomboids and lower traps — the scapular stabilisers that underpin every upper body movement.' },
      { name: 'Arm Circles + Neck Rolls', duration: '30 secs', description: 'Slow controlled arm circles in both directions, then gentle neck rolls. Gets blood into the upper traps, neck and shoulder girdle before the compound movements.' },
    ],
    coolDown: [
      { name: 'Doorway Chest Stretch', duration: '45 secs each side', description: 'Forearm on doorframe, lean through. Restores pec minor and anterior deltoid length after pressing volume.' },
      { name: 'Child\'s Pose with Lat Reach', duration: '45 secs each side', description: 'Kneeling, arms extended forward, walk hands to one side. Decompresses the thoracic spine and stretches the lat after pulling work.' },
      { name: 'Cross-Body Shoulder Stretch', duration: '30 secs each side', description: 'Pull straight arm across chest. Stretches the posterior capsule of the shoulder joint — reduced posterior capsule tightness lowers shoulder injury risk.' },
      { name: 'Wrist Flexor/Extensor Stretch', duration: '20 secs each direction per wrist', description: 'Extend arm, use opposite hand to bend wrist up (extensor stretch) then down (flexor stretch). Forearm and wrist health is critical for long-term pressing and curling capacity.' },
    ],
  },

  saturday: {
    id: 'lower',
    type: 'lower',
    label: 'Lower — Posterior Chain',
    exercises: [
      {
        id: 'rdl_sat',
        name: 'Romanian Deadlift',
        muscleGroups: ['hamstrings', 'glutes', 'back'],
        sets: 4,
        repsMin: 8,
        repsMax: 10,
        restSeconds: 150,
        notes: 'Heaviest RDL of the week',
      },
      {
        id: 'bulgarian_split',
        name: 'Bulgarian Split Squat',
        muscleGroups: ['quads', 'glutes', 'hamstrings'],
        sets: 3,
        repsMin: 10,
        repsMax: 12,
        restSeconds: 120,
        notes: 'Each leg — use DBs for balance first',
      },
      {
        id: 'leg_press_high',
        name: 'Leg Press (Feet High + Wide)',
        muscleGroups: ['glutes', 'hamstrings', 'quads'],
        sets: 3,
        repsMin: 12,
        repsMax: 15,
        restSeconds: 120,
        notes: 'Glute + hamstring emphasis',
      },
      {
        id: 'leg_curl_sat',
        name: 'Lying Leg Curl',
        muscleGroups: ['hamstrings'],
        sets: 4,
        repsMin: 10,
        repsMax: 12,
        restSeconds: 60,
      },
      {
        id: 'hip_thrust',
        name: 'Hip Thrust (Barbell)',
        muscleGroups: ['glutes', 'hamstrings'],
        sets: 3,
        repsMin: 12,
        repsMax: 15,
        restSeconds: 90,
        notes: 'Maximum glute activation — squeeze at top',
      },
      {
        id: 'seated_calf',
        name: 'Seated Calf Raise',
        muscleGroups: ['calves'],
        sets: 4,
        repsMin: 15,
        repsMax: 20,
        restSeconds: 60,
        notes: 'Soleus emphasis',
      },
      {
        id: 'hanging_leg_raise',
        name: 'Hanging Leg Raise',
        muscleGroups: ['core'],
        sets: 3,
        repsMin: 12,
        repsMax: 15,
        restSeconds: 60,
        notes: 'Lower abs',
      },
      {
        id: 'cable_crunch_sat',
        name: 'Cable Crunch',
        muscleGroups: ['core'],
        sets: 3,
        repsMin: 15,
        repsMax: 20,
        restSeconds: 60,
      },
    ],
    warmUp: [
      { name: 'Hip Circles', duration: '10 reps each direction', description: 'Large knee circles while standing on one foot. Mobilises the hip capsule before posterior chain loading — particularly important before heavy RDLs and hip thrusts.' },
      { name: 'Glute Bridges', duration: '20 reps', description: 'Lying on back. Drive hips up, hard glute squeeze at the top. Activates the glutes before you ask them to handle serious load — prevents the hamstrings and spinal erectors from over-compensating.' },
      { name: 'Banded Clamshells', duration: '15 reps each side', description: 'Lie on side, hips bent at 45°, light band above knees. Open top knee like a clamshell. Activates gluteus medius — the hip abductor that stabilises the pelvis during split squats and single-leg movements.' },
      { name: 'Hip Flexor Lunge with Rotation', duration: '30 secs each side', description: 'Rear knee on floor, front foot flat. Reach overhead arm toward the front foot. Opens the hip flexor and thoracic rotation simultaneously — key mobility combo for heavy RDL and split squats.' },
      { name: 'Leg Swings', duration: '10 reps each direction per leg', description: 'Front-to-back and side-to-side. Warms the adductors, hip flexors, hamstrings and glutes dynamically before loaded posterior chain work.' },
    ],
    coolDown: [
      { name: 'Supine Hamstring Stretch', duration: '45 secs each side', description: 'Lie on back, pull one leg toward chest with it as straight as possible. The hamstrings are the primary mover in RDL — static stretching post-session restores resting length and reduces DOMS.' },
      { name: 'Pigeon Pose', duration: '60 secs each side', description: 'One shin across the mat, opposite leg extended back. Sink the hips. The deepest available stretch for the piriformis and glute complex — critical after hip thrusts and split squats.' },
      { name: 'Kneeling Hip Flexor Stretch', duration: '45 secs each side', description: 'Rear knee on floor. Push hips forward gently. RDLs lengthen the hamstrings but the hip flexors stay contracted throughout — this counterbalances that pattern.' },
      { name: 'Seated Butterfly Stretch', duration: '45 secs', description: 'Soles of feet together, let knees fall out. Gentle forward lean. Stretches the adductors and inner groin — often neglected but vital after wide-stance leg press and hip work.' },
      { name: 'Standing IT Band Stretch', duration: '30 secs each side', description: 'Cross one foot behind the other, reach opposite arm overhead and lean away. Stretches the iliotibial band and TFL — commonly tight after heavy single-leg and posterior chain work.' },
    ],
  },

  sunday: null,
};

export const SESSION_LABELS: Record<string, string> = {
  push: 'Push',
  pull: 'Pull',
  legs: 'Legs',
  upper: 'Upper',
  lower: 'Lower',
  rest: 'Rest',
};

export const SESSION_COLORS: Record<string, string> = {
  push: '#3b82f6',
  pull: '#8b5cf6',
  legs: '#22c55e',
  upper: '#f59e0b',
  lower: '#ef4444',
  rest: '#555555',
};
